com/sun/jndi/ldap/LdapDnsProviderTest.java.LdapDnsProviderTest
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux/9/testReport/junit/com_sun_jndi_ldap_LdapDnsProviderTest/java/LdapDnsProviderTest_2/
Fails Hotspot and OpenJ9
```
01:37:37  openjdk version "1.8.0_292"
01:37:37  OpenJDK Runtime Environment (build 1.8.0_292-202103091148-b05)
01:37:37  Eclipse OpenJ9 VM (build openj9-0.26.0-m1, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210309_235 (JIT enabled, AOT enabled)
01:37:37  OpenJ9   - b227feba2
01:37:37  OMR      - 4665e2f72
01:37:37  JCL      - 1780cbc92b based on jdk8u292-b05)
```
```
01:48:22  Testing: ldap://localhost:111/dc=example,dc=com, localhost:111
01:48:22  javax.naming.NamingException: LDAP connection has been closed
01:48:22  	at com.sun.jndi.ldap.LdapRequest.getReplyBer(LdapRequest.java:133)
01:48:22  	at com.sun.jndi.ldap.Connection.readReply(Connection.java:469)
01:48:22  	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365)
01:48:22  	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:192)
01:48:22  	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2897)
01:48:22  	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:347)
01:48:22  	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225)
01:48:22  	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
01:48:22  	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243)
01:48:22  	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
01:48:22  	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
01:48:22  	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
01:48:22  	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
01:48:22  	at javax.naming.InitialContext.init(InitialContext.java:244)
01:48:22  	at javax.naming.InitialContext.<init>(InitialContext.java:216)
01:48:22  	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
01:48:22  	at ProviderTest.call(LdapDnsProviderTest.java:108)
01:48:22  	at ProviderTest.call(LdapDnsProviderTest.java:78)
01:48:22  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01:48:22  	at java.lang.Thread.run(Thread.java:823)
01:48:22  Test failed
01:48:22  Test failed
01:48:22  java.lang.RuntimeException: Test failed, unexpected result
01:48:22  	at LdapDnsProviderTest.runTest(LdapDnsProviderTest.java:221)
01:48:22  	at LdapDnsProviderTest.main(LdapDnsProviderTest.java:196)
01:48:22  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:48:22  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:48:22  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:48:22  	at java.lang.reflect.Method.invoke(Method.java:498)
01:48:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:48:22  	at java.lang.Thread.run(Thread.java:823)
```
Suspect upstream issue?
