Failure link
------------

Public link to the failing test.
If the link is not public, instead include 
- test category (functionality, system, etc): openjdk
- test suite name: BasicLayerTest.testPackageAlreadyInUnnamedModule
- OS/architecture (i.e. Ubuntu 16.04 x64): Ubuntu16.04, but probably any
- OpenJDK version (i.e. 8u202-b08): jdk-11.0.4
- public build SHAs (i.e. -version output): level I tested with:
openjdk version "11.0.4-internal" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4-internal+0-adhoc.admin.jdk11Public)
Eclipse OpenJ9 VM (build master-800cbf79f, JRE 11 Linux amd64-64-Bit Compressed References 20190628_000000 (JIT enabled, AOT enabled)
OpenJ9   - 800cbf79f
OMR      - 6b7c531a
JCL      - f9067eeb59 based on jdk-11.0.4+8)

Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output
--------------
test/jdk/java/lang/ModuleLayer/BasicLayerTest.testPackageAlreadyInUnnamedModule 
this line: 
    ModuleLayer.boot().defineModules(cf, mn -> c.getClassLoader());
does NOT throw the required LayerInstantiationException

Having done some debug, the OpenJ9 native implementation for defineModules needs to validate that the package being defined for the given module within the given classloader does not already exist, which is the case with the testcase.


